packages:
  - apps/*
  - packages/*

catalog:
  '@antfu/eslint-config': ^4.16.2
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@date-fns/tz': ^1.2.0
  '@dicebear/collection': ^9.2.3
  '@dicebear/core': ^9.2.3
  '@iconify-json/circle-flags': ^1.2.6
  '@iconify-json/fluent': ^1.2.26
  '@iconify-json/fluent-emoji-flat': ^1.2.3
  '@iconify-json/lucide': ^1.2.55
  '@iconify-json/simple-icons': ^1.2.41
  '@internationalized/date': ^3.8.2
  '@neoconfetti/vue': ^2.2.1
  '@nuxt/devtools': ^2.6.2
  '@nuxt/image': ^1.10.0
  '@nuxt/ui': ^3.2.0
  '@nuxtjs/i18n': ^9.5.6
  '@paralleldrive/cuid2': ^2.2.2
  '@pinia/nuxt': ^0.11.1
  '@tailwindcss/typography': ^0.5.16
  '@types/node': ^24.0.10
  '@types/pg': ^8.15.4
  '@vitejs/plugin-vue': ^6.0.0
  '@vitest/browser': ^3.2.4
  '@vitest/coverage-v8': ^3.2.4
  '@vueuse/core': ^13.5.0
  '@vueuse/integrations': ^13.5.0
  '@vueuse/nuxt': ^13.5.0
  arktype: ^2.1.20
  aws4fetch: ^1.0.20
  changelogen-monorepo: ^0.5.0
  date-fns: ^4.1.0
  dotenv: ^16.6.1
  dotenv-cli: ^8.0.0
  drizzle-cuid2: ^2.1.0
  drizzle-kit: ^0.31.4
  drizzle-orm: ^0.44.2
  eslint: ^9.30.1
  husky: ^9.1.7
  ioredis: ^5.6.1
  libphonenumber-js: ^1.12.9
  lint-staged: ^16.1.2
  nuxt: ^3.17.6
  nuxt-auth-utils: ^0.5.20
  nuxt-tiptap-editor: ^2.3.1
  nuxt-zod-i18n: ^1.12.0
  pg: ^8.16.3
  pinia: ^3.0.3
  playwright: ^1.53.2
  ru-nalog-fias-gar: ^1.0.4
  sharp: ^0.34.2
  sortablejs: ^1.15.6
  tailwindcss-motion: ^1.1.1
  typescript: ^5.8.3
  unbuild: ^3.5.0
  vite: ^7.0.2
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.2.4
  vitest-browser-vue: ^1.0.0
  vue-tsc: ^2.2.12
  zod: ^3.25.73

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - msw
  - vue-demi

onlyBuiltDependencies:
  - sharp

supportedArchitectures:
  cpu: [x64, arm64]
  os: [linux, darwin, win32]
