packages:
  - apps/*
  - packages/*

catalogs:
  dev:
    '@antfu/eslint-config': ^6.0.0
    '@commitlint/cli': ^20.1.0
    '@commitlint/config-conventional': ^20.0.0
    '@iconify-json/circle-flags': ^1.2.10
    '@iconify-json/fluent': ^1.2.33
    '@iconify-json/fluent-emoji-flat': ^1.2.5
    '@iconify-json/lucide': ^1.2.70
    '@iconify-json/simple-icons': ^1.2.55
    '@nuxt/devtools': ^2.6.5
    '@nuxt/image': ^1.11.0
    '@nuxtjs/i18n': ^10.1.1
    '@tailwindcss/typography': ^0.5.19
    bumpp: ^10.3.1
    dotenv: ^17.2.3
    eruda: ^3.4.3
    eslint: ^9.38.0
    husky: ^9.1.7
    lint-staged: ^16.2.6
    nitropack: ^2.12.7
    nuxt: ^4.1.3
    nuxt-auth-utils: ^0.5.25
    tailwindcss-motion: ^1.1.1
    typescript: ^5.9.3
    vite: ^7.1.12
    vue-tsc: ^3.1.1
  integrations:
    '@date-fns/tz': ^1.4.1
    '@internationalized/date': ^3.10.0
    '@neoconfetti/vue': ^2.2.1
    '@nextorders/queue': ^0.3.0
    '@nuxt/ui': ^4.1.0
    '@openai/agents': ^0.1.9
    '@paralleldrive/cuid2': 2.2.2
    '@pinia/nuxt': ^0.11.2
    '@telegram-apps/init-data-node': ^2.0.10
    '@tma.js/sdk-vue': ^1.0.6
    '@unovis/ts': ^1.6.1
    '@unovis/vue': ^1.6.1
    '@vueuse/components': ^13.9.0
    '@vueuse/core': ^13.9.0
    '@vueuse/integrations': ^13.9.0
    '@vueuse/nuxt': ^13.9.0
    arktype: ^2.1.22
    aws4fetch: ^1.0.20
    date-fns: ^4.1.0
    grammy: ^1.38.3
    ioredis: ^5.8.1
    libphonenumber-js: ^1.12.24
    nuxt-tiptap-editor: ^2.3.1
    nuxt-zod-i18n: ^1.12.1
    openai: ^6.2.0
    pinia: ^3.0.3
    sharp: ^0.34.4
    sortablejs: ^1.15.6
    zod: ^3.25.76
  test:
    '@vitest/browser': ^3.2.4
    '@vitest/coverage-v8': ^3.2.4
    playwright: ^1.56.1
    vitest: ^3.2.4
    vitest-browser-vue: ^1.1.0
  types:
    '@types/node': ^24.9.1

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - msw
  - vue-demi

onlyBuiltDependencies:
  - sharp

supportedArchitectures:
  cpu: [x64, arm64]
  os: [linux, darwin, win32]

nodeLinker: hoisted
autoInstallPeers: true
