packages:
  - apps/*
  - packages/*

catalog:
  '@antfu/eslint-config': ^6.0.0
  '@commitlint/cli': ^20.1.0
  '@commitlint/config-conventional': ^20.0.0
  '@date-fns/tz': ^1.4.1
  '@iconify-json/circle-flags': ^1.2.8
  '@iconify-json/fluent': ^1.2.32
  '@iconify-json/fluent-emoji-flat': ^1.2.5
  '@iconify-json/lucide': ^1.2.69
  '@iconify-json/simple-icons': ^1.2.54
  '@internationalized/date': ^3.10.0
  '@neoconfetti/vue': ^2.2.1
  '@nextorders/queue': ^0.3.0
  '@nuxt/devtools': ^2.6.5
  '@nuxt/image': ^1.11.0
  '@nuxt/ui': ^4.0.1
  '@nuxtjs/i18n': ^10.1.0
  '@openai/agents': ^0.1.9
  '@paralleldrive/cuid2': ^2.2.2
  '@pinia/nuxt': ^0.11.2
  '@tailwindcss/typography': ^0.5.19
  '@telegram-apps/init-data-node': ^2.0.10
  '@telegram-apps/sdk-vue': ^2.0.31
  '@types/node': ^24.7.1
  '@types/pg': ^8.15.5
  '@unovis/ts': ^1.6.1
  '@unovis/vue': ^1.6.1
  '@vitejs/plugin-vue': ^6.0.1
  '@vitest/browser': ^3.2.4
  '@vitest/coverage-v8': ^3.2.4
  '@vueuse/components': ^13.9.0
  '@vueuse/core': ^13.9.0
  '@vueuse/integrations': ^13.9.0
  '@vueuse/nuxt': ^13.9.0
  arktype: ^2.1.22
  aws4fetch: ^1.0.20
  changelogen-monorepo: ^0.5.0
  date-fns: ^4.1.0
  dotenv: ^17.2.3
  drizzle-cuid2: ^2.1.0
  drizzle-kit: ^0.31.5
  drizzle-orm: ^0.44.6
  eruda: ^3.4.3
  eslint: ^9.37.0
  grammy: ^1.38.3
  husky: ^9.1.7
  ioredis: ^5.8.1
  libphonenumber-js: ^1.12.23
  lint-staged: ^16.2.3
  nitropack: latest
  node-xlsx: ^0.24.0
  nuxt: ^4.1.3
  nuxt-auth-utils: ^0.5.25
  nuxt-tiptap-editor: ^2.3.1
  nuxt-zod-i18n: ^1.12.1
  openai: ^6.2.0
  pg: ^8.16.3
  pinia: ^3.0.3
  playwright: ^1.56.0
  ru-nalog-fias-gar: ^1.0.4
  sharp: ^0.34.4
  sortablejs: ^1.15.6
  tailwindcss-motion: ^1.1.1
  typescript: ^5.9.3
  uqr: ^0.1.2
  vite: ^7.1.11
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.2.4
  vitest-browser-vue: ^1.1.0
  vue-tsc: ^3.1.1
  zod: ^3.25.76

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - msw
  - vue-demi

onlyBuiltDependencies:
  - sharp

supportedArchitectures:
  cpu: [x64, arm64]
  os: [linux, darwin, win32]

nodeLinker: hoisted
autoInstallPeers: true
