packages:
  - apps/*
  - packages/*
catalog:
  '@antfu/eslint-config': ^4.13.2
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@date-fns/tz': ^1.2.0
  '@dicebear/collection': ^9.2.2
  '@dicebear/core': ^9.2.2
  '@iconify-json/circle-flags': ^1.2.6
  '@iconify-json/fluent': ^1.2.22
  '@iconify-json/fluent-emoji-flat': ^1.2.3
  '@iconify-json/lucide': ^1.2.44
  '@iconify-json/simple-icons': ^1.2.35
  '@internationalized/date': ^3.8.1
  '@neoconfetti/vue': ^2.2.1
  '@nuxt/devtools': ^2.4.1
  '@nuxt/image': ^1.10.0
  '@nuxt/ui': ^3.1.3
  '@nuxtjs/i18n': ^9.5.4
  '@paralleldrive/cuid2': ^2.2.2
  '@pinia/nuxt': ^0.11.0
  '@tailwindcss/typography': ^0.5.16
  '@types/node': ^22.15.21
  '@types/pg': ^8.15.2
  '@vitejs/plugin-vue': ^5.2.4
  '@vitest/browser': ^3.1.4
  '@vitest/coverage-v8': ^3.1.4
  '@vueuse/core': ^13.2.0
  '@vueuse/integrations': ^13.2.0
  '@vueuse/nuxt': ^13.2.0
  arktype: ^2.1.20
  aws4fetch: ^1.0.20
  changelogen-monorepo: ^0.4.3
  date-fns: ^4.1.0
  dotenv: ^16.5.0
  dotenv-cli: ^8.0.0
  drizzle-cuid2: ^2.0.0
  drizzle-kit: ^0.31.1
  drizzle-orm: ^0.43.1
  eslint: ^9.27.0
  husky: ^9.1.7
  ioredis: ^5.6.1
  libphonenumber-js: ^1.12.8
  lint-staged: ^16.0.0
  nuxt: ^3.17.4
  nuxt-auth-utils: ^0.5.20
  nuxt-tiptap-editor: ^2.2.1
  nuxt-zod-i18n: ^1.11.5
  pg: ^8.16.0
  pinia: ^3.0.2
  playwright: ^1.52.0
  sharp: ^0.34.2
  sortablejs: ^1.15.6
  tailwindcss-motion: ^1.1.0
  typescript: ^5.8.3
  unbuild: ^3.5.0
  vite: ^6.3.5
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.1.4
  vitest-browser-vue: ^0.2.0
  vue-tsc: ^2.2.10
  zod: ^3.25.28
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - msw
  - vue-demi
onlyBuiltDependencies:
  - sharp
supportedArchitectures:
  cpu: [x64, arm64]
  os: [linux, darwin, win32]
