packages:
  - apps/*
  - packages/*

catalogs:
  dev:
    '@antfu/eslint-config': ^6.4.2
    '@commitlint/cli': ^20.2.0
    '@commitlint/config-conventional': ^20.2.0
    '@iconify-json/circle-flags': ^1.2.10
    '@iconify-json/fluent': ^1.2.36
    '@iconify-json/fluent-emoji-flat': ^1.2.5
    '@iconify-json/lucide': ^1.2.79
    '@iconify-json/simple-icons': ^1.2.61
    '@nuxt/devtools': ^3.1.1
    '@nuxt/image': ^1.11.0
    '@nuxtjs/i18n': ^10.2.1
    '@tailwindcss/typography': ^0.5.19
    bumpp: ^10.3.2
    dotenv: ^17.2.3
    eruda: ^3.4.3
    eslint: ^9.39.1
    husky: ^9.1.7
    lint-staged: ^16.2.7
    nitropack: ^2.12.9
    nuxt: ^4.2.1
    nuxt-auth-utils: ^0.5.25
    tailwindcss-motion: ^1.1.1
    typescript: ^5.9.3
    vite: ^7.2.6
    vue-tsc: ^3.1.6
  integrations:
    '@date-fns/tz': ^1.4.1
    '@internationalized/date': ^3.10.0
    '@neoconfetti/vue': ^2.2.1
    '@nextorders/queue': ^0.4.2
    '@nuxt/ui': ^4.2.1
    '@openai/agents': ^0.3.4
    '@paralleldrive/cuid2': 2.3.1
    '@pinia/nuxt': ^0.11.3
    '@telegram-apps/init-data-node': ^2.0.10
    '@tma.js/sdk-vue': ^1.0.11
    '@unovis/ts': ^1.6.2
    '@unovis/vue': ^1.6.2
    '@vueuse/components': ^13.9.0
    '@vueuse/core': ^13.9.0
    '@vueuse/integrations': ^13.9.0
    '@vueuse/nuxt': ^13.9.0
    arktype: ^2.1.28
    aws4fetch: ^1.0.20
    date-fns: ^4.1.0
    grammy: ^1.38.4
    ioredis: ^5.8.2
    libphonenumber-js: ^1.12.31
    nuxt-tiptap-editor: ^2.3.1
    nuxt-zod-i18n: ^1.12.1
    openai: ^6.10.0
    pinia: ^3.0.4
    sharp: ^0.34.5
    sortablejs: ^1.15.6
    zod: ^3.25.76
  test:
    '@vitest/browser-playwright': ^4.0.15
    '@vitest/coverage-v8': ^4.0.15
    playwright: ^1.57.0
    vitest: ^4.0.15
    vitest-browser-vue: ^2.0.1
  types:
    '@types/node': ^24.10.1

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - msw
  - vue-demi

onlyBuiltDependencies:
  - sharp

supportedArchitectures:
  cpu: [x64, arm64]
  os: [linux, darwin, win32]

nodeLinker: hoisted
autoInstallPeers: true
