services:
  db:
    image: postgres:17
    ports:
      - 5433:5432
    volumes:
      - sushi_atrium_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

volumes:
  sushi_atrium_data:
