name: CI

on:
  push:
    paths-ignore:
      - "*.md"
      - "docker/**"
      - ".github/**"
      - "!.github/workflows/ci.yml"
    branches:
      - main
  pull_request:
    paths-ignore:
      - "*.md"
      - "docker/**"
      - ".github/**"
      - "!.github/workflows/ci.yml"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PNPM
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: ESLint
        run: pnpm run lint

      - name: Typecheck
        run: pnpm run typecheck

      - name: Test
        run: pnpm run test

      - name: Build
        run: pnpm run build
